#!/usr/bin/env python3
"""Pre-commit check: Prevent one-time scripts from being committed to /scripts/.

Inspects staged files under scripts/ for one-time markers (RULE-12).
Intended to run as a Git pre-commit hook or in CI.

Usage:
    python3 scripts/check_no_onetime_in_scripts.py

Exit codes:
    0: No violations — safe to commit
    1: One-time script detected in /scripts/ — commit blocked

Setup (manual — add to .git/hooks/pre-commit):
    #!/bin/sh
    python3 scripts/check_no_onetime_in_scripts.py
"""

import re
import subprocess
import sys

# Patterns that indicate a one-time/session-specific script
ONE_TIME_MARKERS = [
    r"session_id\s*=",
    r"tmp/.*\.json",
    r"one[_-]?time",
    r"single[_-]?use",
    r"disposable",
    r"temporary\s+script",
    r"# Generated by .* at \d{4}-\d{2}-\d{2}",
    r"# Auto-generated for session",
]


def get_staged_scripts():
    """Get list of staged files under scripts/."""
    try:
        result = subprocess.run(
            ["git", "diff", "--staged", "--name-only", "--diff-filter=ACM"],
            capture_output=True, text=True, check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    return [f for f in result.stdout.strip().split("\n") if f.startswith("scripts/") and f.endswith(".py")]


def check_file_for_markers(filepath):
    """Check if a file contains one-time markers."""
    try:
        with open(filepath, encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except OSError:
        return []
    found = []
    for pattern in ONE_TIME_MARKERS:
        matches = re.findall(pattern, content, re.IGNORECASE)
        if matches:
            found.append(pattern)
    return found


def main():
    staged = get_staged_scripts()
    if not staged:
        sys.exit(0)

    violations = []
    for filepath in staged:
        markers = check_file_for_markers(filepath)
        if markers:
            violations.append((filepath, markers))

    if not violations:
        sys.exit(0)

    print("RULE-12 VIOLATION: One-time script(s) detected in /scripts/")
    print("Move these to /tmp/scripts/ before committing:\n")
    for filepath, markers in violations:
        print(f"  {filepath}")
        for m in markers:
            print(f"    - matched: {m}")
    print("\nSee RULE-12 in .github/RULE.md for details.")
    print("Run: python3 scripts/validate_script_placement.py to auto-relocate.")
    sys.exit(1)


if __name__ == "__main__":
    main()
